apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: reconpoint-cert
  namespace: default
spec:
  secretName: reconpoint-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - reconpoint.example.com